# Generated by Django 5.0.6 on 2024-06-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=50)),
                ('course_amount', models.IntegerField()),
            ],
        ),
    ]
