# Generated by Django 5.0.6 on 2024-06-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearn_app', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
