# Generated by Django 5.0.6 on 2024-06-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearn_app', '0003_course_course_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_link',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
