# Generated by Django 5.0.6 on 2024-06-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearn_app', '0005_mycourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
