# Generated by Django 5.0.6 on 2024-06-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearn_app', '0007_mycourse_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourse',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='user_name',
        ),
    ]
