# Generated by Django 5.0.6 on 2024-06-29 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearn_app', '0008_remove_mycourse_course_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mycourse',
            unique_together={('user', 'course')},
        ),
    ]
